homepage:
    path: /
    defaults: { _controller: TestHubBundle:Test:index }

start:
    path: /test/{testID}/start
    defaults: { _controller: TestHubBundle:Test:start }
    methods: [POST]

preface:
    path: /test/{testID}/preface
    defaults: { _controller: TestHubBundle:Test:preface }

question:
    path: /attempt/{attemptID}/question/{questionNumber}
    defaults: { _controller: TestHubBundle:Test:question }
    requirements:
        questionNumber: \d+
        attemptID: \d+

result:
    path: /result/{attemptID}
    defaults: { _controller: TestHubBundle:Test:result }

confirm:
    path: /attempt/{attemptID}/confirm
    defaults: { _controller: TestHubBundle:Test:confirm }
