# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    user_manager:
        class: AppBundle\Service\DummyUserManager
        arguments: ["@doctrine.orm.entity_manager"]
    test_service:
        class: AppBundle\Service\TestService
        arguments: ["@doctrine.orm.entity_manager"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
