<?php
namespace TestHubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariantRepository extends EntityRepository
{
}
